# Train Test Split Function

In [31]:
# Importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Download the dataset using following link,

(https://www.dropbox.com/s/uh7o7uyeghqkhoy/diabetes.csv?dl=0)

In [32]:
# Loading the dataset to pandas DataFrame
db_df = pd.read_csv("/content/diab_data.csv")

In [33]:
db_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [34]:
db_df.shape

(768, 9)

The Labels

In [35]:
# Counting labels of 'Outcome' feature
db_df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

Splitting The Data Into Features & Targets/Labels

In [36]:
# The features
X = db_df.drop(columns = "Outcome", axis = 1)
# The targets/labels
Y = db_df["Outcome"]

In [37]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [38]:
Y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

# Standardizing The Data

To Make The Data In Common Range

In [39]:
# Checking standard deviation in X
X.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
dtype: float64

In [40]:
# Using StandardScaler function for standardizing
scaler = StandardScaler()
scaler.fit(X)
stndrd_data = scaler.transform(X)

In [41]:
# Checking standard deviation in standardized X data
stndrd_data.std()

np.float64(1.0)

In [42]:
X = stndrd_data
Y = db_df["Outcome"]

# Splitting The Data Into Training & Testing Data

In [43]:
# Using train test split function for splitting
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)
# 'test_size = 0.2' mean 20% of data will be test data and 80% will be the train data.

In [44]:
print(f"X Shape:{X.shape}\nY Shape:{Y.shape}\nTrain-X Shape:{X_train.shape}\nTest-X Shape:{X_test.shape}\nTrain-Y Shape:{Y_train.shape}\nTest-Y Shape:{Y_test.shape}")

X Shape:(768, 8)
Y Shape:(768,)
Train-X Shape:(614, 8)
Test-X Shape:(154, 8)
Train-Y Shape:(614,)
Test-Y Shape:(154,)